name: NetDevPack - MASTER Publish

on:
  push:
    branches: [ master ]

env:
  REPOSITORY_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  CURRENT_REPO_URL: https://github.com/${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            6.0.x
            5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Semantic Release + Plugins
        run: |
          npm init -y
          npm install semantic-release @semantic-release/changelog @semantic-release/github @semantic-release/git --legacy-peer-deps

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Package
        run: dotnet pack -c Release -o out -p:RepositoryUrl=${{env.CURRENT_REPO_URL}}

      - name: Publish the package to nuget.org
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true -k ${{ secrets.NUGET_AUTH_TOKEN }} -s https://api.nuget.org/v3/index.json
